@startuml

[*] --> DRAFT;
DRAFT: can be edited
DRAFT --> ACTIVE;
ACTIVE : cannot be edited;
ACTIVE : can be used to create runs;
ACTIVE --> OBSOLETE;
OBSOLETE : cannot be edited;
OBSOLETE: cannot be used to create runs;
OBSOLETE --> ACTIVE;

@enduml
