= Approaches to Platform Flows
David Watkins<david.watkins@db.com>;
Mark Guerriero<mark.guerriero@db.com>;
:toc:

== Overview

This document looks at how Waltz could be adapted to enhance it's support for _platform_ applications.
It looks at how flows are represented, how lineage can be achieved and how attestations are used.

== High Level Recommendations

* Adopt attestation exclusion mechanism for platform
** Obligation for attestation moves to providers of data to platforms
* Invest in lineage interop with external tooling
** Enhance flow diagrams / waltz support for 'first pass' lineage
* Altering flow representation (e.g. 'via' attributes) will complicate solution for little incremental value

<<<

== Overview of current model

The diagram below shows a simplified version of the model used by Waltz to represent flows.

_Logical flows_ connect two endpoints, which are typically applications.
The logical flows can be decorated with _data types_ (not shown).

Each logical flow may have _physical flows_ associated with it.
Each physical flows has a _physical specification_ which describes the content of the data.
Physical specifications can be reused across physical flows.


.Current flow model
[graphviz, merged, svg]
----
digraph B {
    app1[label="Source\nApplication", color="green"];
    app2[label="Target\nApplication", color="green"];

    lf1_2[label="App1 &raquo; App2\nLogical Flow", shape=box, color=darkgreen, style=solid];

    pf1[label="0839_LS2_CON.dat\nPhysical Flow", shape=box, style=solid, color=darkblue];
    pf2[label="0840_LS2_CON.dat\nPhysical Flow", shape=box, style=solid, color=darkblue];

    ps[label="XXX_LS2_CON.dat\nPhysical Spec", shape=box, style=dashed, color=blue];

    app1 -> lf1_2 -> app2;

    lf1_2-> pf1;
    lf1_2 -> pf2;

    pf1 -> ps;
    pf2 -> ps;

    {rank = same; app1; app2; lf1_2}
}
----

Waltz's flow database is made up from numerous point to point logical flows and their physical counterparts. The totality of those flows represents the known flow network and can be represented as a directed graph.

=== Lineage

Lineage can be thought of as a pathway taken though the logical flow directed graph.  Starting from a source node, traversing logical flows, to reach a target node.

.Lineage using the existing Waltz model
[graphviz, direct, svg]
----
digraph B {
    plat[label="Platform", color="orange"];
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];

    lf1[label="App1 &raquo; Plat\nLogical Flow", shape=box, color=darkgreen, style=solid];
    lf2[label="Plat &raquo; App2\nLogical Flow", shape=box, color=darkgreen, style=solid];

    app1 -> lf1 -> plat -> lf2 -> app2;

    app1 -> app2 [style=dotted]
    {rank = same; app1; app2; lf1; lf2, plat}
}
----

In Waltz there are limited ways to express indirect flow relationships such as `App 1` -> `App 2` in the diagram above (shown with the dotted arc).
To show lineage users have a choice:

* Use **Waltz's Flow Diagram** capabilities which allow users to quickly draw a route through the network (by using an editor constrained by the underlying graph).
* Use **physical flow tagging** to associated flows.
  This is conceptually similar to the diagrams mentioned above, but some users prefer this basic approach.
* **Export the flows and use tools** such as Solidatus to represent a more detailed view of lineage


<<<

=== Attestation
In the current model we view the **consuming application as the owner of the flow**.
The reasoning behind this is based on a simple belief that the consumer is more likely to be aware of the flow than the producer.

For simple app-to-app flows systems this model works well and attestation is straightforward; the consumer should attest all inbound flows.
This is depicted in the figure below (`App C` must attest to the accuracy of the flows from `A` and `B`).

.Example of attestation scope for simple apps
[graphviz, direct-att-simple, svg]
----
digraph B {
    A[label="App A", color="green"];
    B[label="App B", color="green"];
    C[label="App C", color="blue"];
    D[label="App D"];

    A->C[color=blue];
    B->C[color=blue];
    C->D[color=balck];
}
----

However, when we have aggregation/distribution platforms the **attestation burden falls upon the platform**.
Often the platform owners are not in a position to be able to accurately perform the required attestation, especially in multi-tenancy situations.


.Direct attestation for platforms
[graphviz, direct-att-complex, svg]
----
digraph B {

    plat[label="Platform\n:(", color="orange"];
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];
    app3[label="App3", color="green"];
    app4[label="App4", color="green"];
    app5[label="App5", color="green"];
    appN[label="...", color="green"];
    app6[label="App6"];
    app7[label="App7"];
    app8[label="App8"];
    app9[label="App9"];
    appNN[label="..."];

    app1 -> plat [color="orange"];
    app2 -> plat [color="orange"];
    app3 -> plat [color="orange"];
    app4 -> plat [color="orange"];
    app5 -> plat [color="orange"];
    appN -> plat [style="dashed"; color="orange"];
    plat -> app6 [color="grey"];
    plat -> app7 [color="grey"];
    plat -> app8 [color="grey"];
    plat -> app9 [color="grey"];
    plat -> appNN [style="dashed"; color="grey"];
}
----

This is depicted in the following figure, the green flows show a large volume of inbound flows to the platform which may have little knowledge of their content and/or accuracy.

<<<

==== Attestation Enhancements

To overcome this situation we could:

**_Option 1:_ Exempt platform _applications_** from flow attestations.
This could be achieved via a simple flag, assessment or membership of a group.
To ensure the flows are attested, the obligation to attest would move to the providers of data to a platform.

.Exempting platforms
[graphviz, direct-att-complex-option-1, svg]
----
digraph B {

    plat[label="Platform\n:)", color="orange"];
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];
    app3[label="App3", color="green"];
    app4[label="App4", color="green"];
    app5[label="App5", color="green"];
    appN[label="...", color="green"];
    app6[label="App6"];
    app7[label="App7"];
    app8[label="App8"];
    app9[label="App9"];
    appNN[label="..."];

    app1 -> plat [color="green"];
    app2 -> plat [color="green"];
    app3 -> plat [color="green"];
    app4 -> plat [color="green"];
    app5 -> plat [color="green"];
    appN -> plat [style="dashed"; color="green"];
    plat -> app6 [color="grey"];
    plat -> app7 [color="grey"];
    plat -> app8 [color="grey"];
    plat -> app9 [color="grey"];
    plat -> appNN [style="dashed"; color="grey"];
}
----

[CAUTION]
====
We would need to consider what happens when/if platforms exchange data.
If they are exempt who has the attestation obligation ?

.Platform to platform flows, who attests ?
[graphviz, direct-att-complex-edge-case, svg]
----
digraph B {

    plat1[label="Platform 1", color="orange"];
    plat2[label="Platform 2", color="orange"];
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];

    app1 -> plat1 [color="green"];
    plat1 -> plat2 [color="red"];
    plat2 -> app2 [color="green"];

    {rank = same; app1; app2; plat1; plat2}
}
----
====

**_Option 2:_ Declare attestation obligations on a per flow basis**, this would be at the physical flow and/or logical flow level.
These obligations will inform the ui who is responsible for each attestation.

Whilst the second option will give more accurate results and handles more situations, we believe the development effort and associated runtime attestation effort will outstrip this gain.


<<<

== Alternative flow representations

=== 'Via' routing

In this approach the flow of data is recorded between `App1` and `App2`.
The platform in between them is recorded as a detail on the physical flow.


.Platforms using physical routing
[graphviz, via, svg]
----
digraph B {
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];
    plat[label="Platform", color="orange"];

    lf1[label="App1 &raquo; App2\nLogical Flow", shape=box, color=darkgreen, style=solid];

    pf1[label="Physical Flow", shape=box, style=solid, color=darkblue];

    app1 -> lf1 -> app2;

    lf1 -> pf1;

    pf1 -> plat [label=" 'via'"];

    {rank = same; app1; app2; lf1}

}
----


|===
|Pros |Cons

| Simplifies basic lineage
| Multi-hop _via_ routes difficult to express (ordering etc)

| Intuitive understanding
| Usage of platforms more difficult to understand as may be via a direct flow or an indirect detail on the physical flow.

| Somewhat solves the attestation problem as the flow is now between apps.
| By omitting the platform from the main flow all recipients must know about, and record, `App 1` as the originator.


|===

<<<


=== 'Ultimate Recipient' routing

A variation of _via routing_ is to store the intended recipient as an optional (list?) attribute on the physical flow.


.Platforms using physical routing
[graphviz, ultimate, svg]
----
digraph B {
    app1[label="App1", color="green"];
    app2[label="App2", color="green"];
    plat[label="Platform", color="orange"];

    lf1[label="App1 &raquo; App2\nLogical Flow", shape=box, color=darkgreen, style=solid];

    pf1[label="Physical Flow", shape=box, style=solid, color=darkblue];

    app1 -> lf1 -> plat;

    lf1 -> pf1;

    pf1 -> app2 [label="  ultimate recipient"];

    {rank = same; app1; plat; lf1}
}
----


|===
|Pros |Cons

| Simplifies extension to current model
| Multi-hop _via_ cannot be expressed

| Can be incrementally/partially adopted
| Yet another way to represent lineage

|===

<<<

=== Layers

This approach proposes additional layers of flows.
Waltz currently has two layers of flows; logical and physical.
Additional layers could be introduced which allow for different views of data movement.
An example could be a 'Data at rest' layer which omits all processing-only nodes





<<<


== Appendix: Waltz terminology

This section defines what specific terms mean in this document

* *Logical Flow*, abstractly describes all flows between two entities (typically apps)
* *Physical Flow*, a specific instance of a _logical flow_
* *Physical Specification*, details of what is being transferred in a _physical flow_
* *Data Types*, hierarchical structure representing all types of data within the organization
* *Measurable Category*, (aka _Taxonomy_)
* *Measurables*, hierarchical structure representing items in a _measurable category_
* *Rating Scheme / Item*, used to describe the relationship between entities (typically apps) and _measurables_
* *Measurable Rating*, the actual linkage of an entity to a _measurable_ using a _rating scheme item_

