package com.khartec.waltz.model.scheduled_job;

public enum JobKey {
    HIERARCHY_REBUILD_CHANGE_INITIATIVE,
    HIERARCHY_REBUILD_DATA_TYPE,
    HIERARCHY_REBUILD_ENTITY_STATISTICS,
    HIERARCHY_REBUILD_MEASURABLE,
    HIERARCHY_REBUILD_ORG_UNIT,
    HIERARCHY_REBUILD_PERSON,

    DATA_TYPE_USAGE_RECALC_APPLICATION,
    COMPLEXITY_REBUILD,
    AUTH_SOURCE_RECALC_FLOW_RATINGS,
    LOGICAL_FLOW_CLEANUP_ORPHANS,
    ATTESTATION_CLEANUP_ORPHANS
}
