= Application environments
Jessica Woodland-Scott <jessica.woodland-scott@db.com>
:version: v0.1
:modified: 2021-04-14
:status: DRAFT
:toc:

<<<
== Document Info

|===
| Attribute | Value

| Status
| {status} {version} ({modified})

| Target Version
| 1.32

| Lead
| Jessica Woodland-Scott
|===

<<<

== Overview

Desire to tag multiple servers and databases to show they belong to a specific environment on an application.

e.g. sever-1, server-2 and database-1 all belong to 'UAT'.


How is this different from the environment field on server_usage/database_information?

* Can give custom/multiple environment names = e.g. 'INT-1', 'INT-2'.
* Can show that servers/databases on used by other applications are a key part of the application environment


Changes:

* Need to be able to create/update/delete environment tags (app specific?)
* Need to be able to link this environment tag to servers and databases (even those not directly used by the application)
* Need screen to show databases and servers linked to an environment


Using existing tags:

* Currently, tags belong to an entityKind - for example 'APPLICATION' which indicates the entity it can be
applied to - wouldn't allow tags to be shared between databases and servers
** wouldn't link back to a specific application
** feels like we need something more like an app group but where the group belongs to a specific app and
you can add any servers or databases to be linked to it




<<<
== Proposal

=== Core Waltz changes

Environment tags will be linked to database_information table and server_usage table? Server information table doesn't give the
app-server information - one server information record can be linked to many apps?

If we're using server_usage though it will need an id...

Although think UAT and Dev2 same server... could just apply two tags to same server?
But say that server was also used by another app... does that matter... surely we want to link the
specific app server to show what is part of the env?

- Could offer warnings where an environment is constructed with servers both from dev and from prod?

Possible tables:

.app_environment_tag:
|===
| id | application_id | name | description | external_id

| 1
| 12345
| INT-1
| Second development environment without nightly database restore
| WALTZ_INT
|===


.app_environment_tag_usage:

|===
|tag_id|entity_id|entity_kind|created_at|created_by|provenance

|1
|678
|DATABASE
|2021-04-14
|admin
|waltz

|1
|91011
|SERVER
|2021-04-14
|admin
|waltz

|1
|121314
|SERVER
|2021-04-14
|admin
|waltz
|===

<<<


== Appendices
