export const REQUEST_PERSON = 'REQUEST_PERSON';
export const RECEIVE_PERSON = 'RECEIVE_PERSON';

export const REQUEST_PERSON_PORTFOLIO = 'REQUEST_PERSON_PORTFOLIO';
export const RECEIVE_PERSON_PORTFOLIO = 'RECEIVE_PERSON_PORTFOLIO';

export const REQUEST_PERSON_PORTFOLIO_REPORT_CONFIG = 'REQUEST_PERSON_PORTFOLIO_REPORT_CONFIG';
export const RECEIVE_PERSON_PORTFOLIO_REPORT_CONFIG = 'RECEIVE_PERSON_PORTFOLIO_REPORT_CONFIG';
