export const characters = [
    "Hannah Abbott – Hufflepuff student in Harry Potter's year. Prefect and member of Dumbledore's Army. Married to Neville Longbottom.",
    "Ludo Bagman – Head of the Department of Magical Games and Sports within the Ministry of Magic.",
    "Bathilda Bagshot – Author of A History of Magic, and the great aunt of Gellert Grindelwald.",
    "Katie Bell – Gryffindor Quidditch Chaser one year above Harry Potter. Member of Dumbledore's Army.",
    "Cuthbert Binns – ghost, History of Magic professor.",
    "Phineas Nigellus Black – Great-great-grandfather of Sirius Black and former Hogwarts headmaster. His painting hangs in the office and assists the current headmaster.",
    "Sirius Black – Harry's godfather who was a close friend of Harry's father James. Escapee from Azkaban prison and member of the Order of the Phoenix. Killed in the Battle of the Department of Mysteries by his cousin Bellatrix Lestrange.",
    "Amelia Bones – Head of the Department of Magical Law Enforcement, and the aunt of Susan Bones. Killed by Lord Voldemort.",
    "Susan Bones – Hufflepuff student in Harry's year. Member of Dumbledore's Army.",
    "Terry Boot – Ravenclaw student in Harry's year. Member of Dumbledore's Army.",
    "Lavender Brown – Gryffindor student in Harry's year and member of Dumbledore's Army. Killed in the Battle of Hogwarts.",
    "Millicent Bulstrode – Slytherin student in Harry's year. Member of Dolores Umbridge's Inquisitorial Squad.",
    "Charity Burbage – Professor of Muggle Studies at Hogwarts. Killed by Lord Voldemort.",
    "Frank Bryce – Muggle gardener for the Riddle family. Killed by Lord Voldemort.",
    "Alecto Carrow – Death Eater and sister of Amycus Carrow. Professor of Muggle Studies for one year, and Deputy Headmistress of Hogwarts under Severus Snape.",
    "Amycus Carrow – Death Eater and brother of Alecto Carrow. Professor of Defence Against the Dark Arts for one year, and Deputy Headmaster of Hogwarts under Snape.",
    "Reginald Cattermole – Employee of the Magical Maintenance Department for the Ministry of Magic. Impersonated by Ron Weasley.",
    "Cho Chang – Ravenclaw Quidditch Seeker one year above Harry, and his first love interest. Member of Dumbledore's Army.",
    "Penelope Clearwater – Ravenclaw prefect and girlfriend of Percy Weasley.",
    "Crabbe – Death Eater and father of Vincent Crabbe.",
    "Vincent Crabbe – Slytherin student in Harry's year and the son of a Death Eater. Slytherin Quidditch Beater and member of the Inquisitorial Squad. Killed by his own Fiendfyre spell.",
    "Colin Creevey – Muggle-born Gryffindor student one year below Harry. Older brother of Dennis Creevey, and member of Dumbledore's Army. Killed during the Battle of Hogwarts.",
    "Dennis Creevey – Muggle-born Gryffindor student three years below Harry. Younger brother of Colin Creevey, and member of Dumbledore's Army.",
    "Dirk Cresswell – Muggle-born Head of the Goblin Liaison Office, went on the run with fellow Muggle-borns Ted Tonks, Dean Thomas and goblins Gornuk and Griphook, during which he is killed.",
    "Barty Crouch Sr – Head of the Department of International Magical Cooperation. Killed by his son Barty Crouch Jr.",
    "Barty Crouch Jr – Death Eater credited with facilitating the return of Lord Voldemort. Used Polyjuice Potion to impersonate Alastor Moody, and received a Dementor's Kiss.",
    "John Dawlish – an Auror.",
    "Fleur Delacour – Participant in the Triwizard Tournament as a representative of wizarding school Beauxbatons. Later married Bill Weasley.",
    "Gabrielle Delacour – Fleur's younger sister. Rescued by Harry during the Triwizard Tournament.",
    "Dedalus Diggle – Member of the Order of the Phoenix who took the Dursleys into hiding.",
    "Amos Diggory – Cedric Diggory's father. Employee of the Department for the Regulation and Control of Magical Creatures.",
    "Cedric Diggory – Hufflepuff student and prefect two years above Harry. Quidditch Seeker and captain, and co-winner of the Triwizard Tournament. Killed by Peter Pettigrew on Lord Voldemort's command.",
    "Elphias Doge – A school friend of Albus Dumbledore.",
    "Antonin Dolohov – Death Eater who killed Fabian Prewett, Gideon Prewett, and Remus Lupin.",
    "Aberforth Dumbledore – Brother of Albus and Ariana Dumbledore. Owner of the Hog's Head tavern.",
    "Albus Dumbledore – Transfiguration professor in Tom Riddle's time, and Hogwarts headmaster in Harry Potter's time. Founder of the Order of the Phoenix. Killed by Severus Snape on Dumbledore's request.",
    "Ariana Dumbledore – Sister of Albus and Aberforth Dumbledore, killed in a three-way duel between her brothers and Gellert Grindelwald.",
    "Kendra Dumbledore – Wife of Percival Dumbledore. Mother of Albus, Aberforth, and Ariana Dumbledore.",
    "Percival Dumbledore – Husband of Kendra Dumbledore, father of Albus, Aberforth, and Ariana Dumbledore.",
    "Dudley Dursley – Muggle son of Vernon Dursley and Petunia Evans, first cousin of Harry Potter.",
    "Marge Dursley – Muggle sister of Vernon Dursley.",
    "Petunia Dursley – Harry's aunt, and his mother Lily's sister. Vernon's wife and Dudley's mother.",
    "Vernon Dursley – Harry Potter's Muggle uncle. Petunia's husband and Dudley's father.",
    "Marietta Edgecombe – Ravenclaw student one year above Harry. Member of Dumbledore's Army who later betrays the group to Dolores Umbridge.",
    "Arabella Figg – Squib neighbour of the Dursleys. Member of the Order of the Phoenix.",
    "Argus Filch – Squib caretaker of Hogwarts.",
    "Justin Finch-Fletchley – Muggle-born Hufflepuff student in Harry's year. Member of Dumbledore's Army.",
    "Seamus Finnigan – Gryffindor student in Harry's year. Member of Dumbledore's Army.",
    "Nicolas Flamel – Creator and owner of the Philosopher's Stone.",
    "Mundungus Fletcher – Common thief and shifty Order of the Phoenix member.",
    "Filius Flitwick – Head of Ravenclaw House and Charms professor at Hogwarts.",
    "Cornelius Fudge – Minister for Magic in the first five books. Sacked after persistently denying Lord Voldemort's return.",
    "Marvolo Gaunt – The pure-blood father of Merope and Morfin Gaunt, and grandfather of Tom Marvolo Riddle.",
    "Merope Gaunt – Tom Riddle's mother who died in childbirth.",
    "Morfin Gaunt – Marvolo's son and Merope's brother. Framed by his nephew Tom Riddle for Muggle killings, and died in Azkaban.",
    "Anthony Goldstein – Ravenclaw student in Harry's year. Member of Dumbledore's Army.",
    "Goyle – Death Eater and father of Gregory Goyle.",
    "Gregory Goyle – Slytherin student in Harry's year. Slytherin Quidditch Beater and member of the Inquisitorial Squad.",
    "Hermione Granger – Muggle-born Gryffindor student in Harry's year and one of his best friends. Prefect and co-founder of Dumbledore's Army.",
    "Astoria Greengrass – Draco Malfoy's wife. She died in 2019 due to her blood curse.",
    "Gregorovitch – highly regarded Eastern European wandmaker.",
    "Fenrir Greyback – Werewolf working for the Death Eaters.",
    "Gellert Grindelwald – Dark wizard who was jailed after Albus Dumbledore defeated him in the 1940s.",
    "Wilhelmina Grubbly-Plank – Substitute Care of Magical Creatures professor during Harry's fourth and fifth years.",
    "Godric Gryffindor – One of the four founders of Hogwarts. He was a very powerful wizard.",
    "Rubeus Hagrid – Half-giant Hogwarts gamekeeper, and Care of Magical Creatures professor starting in Harry's third year. Member of the Order of the Phoenix. As a Hogwarts student, he was expelled in his third year.",
    "Rolanda Hooch – Hogwarts flying instructor and Quidditch referee.",
    "Mafalda Hopkirk – Witch who works in the Ministry of Magic. Impersonated by Hermione Granger.",
    "Helga Hufflepuff- Founder of Hufflepuff House. Co-founder of Hogwarts School of Witchcraft and Wizardry.",
    "Angelina Johnson – Gryffindor student two years above Harry. Quidditch Chaser and later team captain.",
    "Lee Jordan – Gryffindor student two years above Harry. Hogwarts Quidditch commentator and good friend of Fred and George Weasley.",
    "Bertha Jorkins – Ministry of Magic employee that worked under the Department of Magical Games and Sports. Killed by Voldemort in order to create Nagini as the last horcrux.",
    "Igor Karkaroff – Reformed Death Eater. Headmaster of wizarding school Durmstrang.",
    "Viktor Krum – Bulgarian Quidditch Seeker and Durmstrang student who participated in the Triwizard Tournament.",
    "Silvanus Kettleburn – Care of Magical Creatures teacher until Harry's third year.",
    "Bellatrix Lestrange – Cousin of Sirius Black. Death Eater who tortured Neville Longbottom's parents Frank and Alice into insanity. Killed by Molly Weasley during the Battle of Hogwarts.",
    "Gilderoy Lockhart – Fraudulent celebrity author and Defence Against the Dark Arts teacher. Lost his memory after a memory charm backfired and resided in St. Mungo's afterwards.",
    "Alice and Frank Longbottom – Neville Longbottom's parents. Aurors and members of the original Order of the Phoenix. Tortured into insanity by Bellatrix Lestrange.",
    "Augusta Longbottom – Frank's mother and Neville's grandmother, who raises him after his parents are incapacitated.",
    "Neville Longbottom – Gryffindor student in Harry's year. Member of Dumbledore's Army.",
    "Luna Lovegood – Xenophilius Lovegood's daughter and Ravenclaw student one year below Harry. Member of Dumbledore's Army and wife of Newt Scamander's grandson Rolf.",
    "Xenophilius Lovegood – Luna's father. Editor of tabloid magazine The Quibbler.",
    "Remus Lupin – Lycanthropic Gryffindor student before Harry's time who befriended Sirius Black and James Potter. Professor of Defence Against the Dark Arts in Harry's third year, and member of the Order of the Phoenix. He and his wife Nymphadora Tonks gave birth to a son, Teddy, before dying in the Battle of Hogwarts.",
    "Walden Macnair – Death Eater and Committee of Disposal of Dangerous Creatures' executioner. Injured badly by Hagrid during the Battle of Hogwarts.",
    "Draco Malfoy – Slytherin student in Harry's year. Quidditch Seeker, prefect, and member of the Inquisitorial Squad.",
    "Lucius Malfoy – Draco's father and an influential Death Eater. Governor of Hogwarts early in the series.",
    "Narcissa Malfoy – Lucius' wife and Draco's mother. Sister of Bellatrix Lestrange and Andromeda Tonks.",
    "Scorpius Malfoy – Son of Draco Malfoy and Astoria Greengrass. Sorted into Slytherin. Friends with Albus Potter.",
    "Madam Malkin – Clothing shop owner in Diagon Alley.",
    "Griselda Marchbanks – Governor of the Wizarding Examinations Authority which ran the O.W.L, N.E.W.T., and W.O.M.B.A.T. exams. Wizengamot elder.",
    "Olympe Maxime – Half-giantess. Headmistress of Beauxbatons.",
    "Ernie Macmillan – Hufflepuff student in Harry's year. Prefect and member of Dumbledore's Army.",
    "Minerva McGonagall – Hogwarts Transfiguration professor, Head of Gryffindor House, Deputy Headmistress of Hogwarts, and member of the Order of the Phoenix. Assumes position of Hogwarts Headmaster for a time after Voldemort's death.",
    "Eloise Midgen – Gryffindor student that accidentally removed her nose trying to get rid of her acne. Known for her bad case of acne.",
    "Cormac McLaggen – Gryffindor student one year above Harry Potter. Quidditch Keeper and member of Horace Slughorn's Slug Club.",
    "Graham Montague – Slytherin Quidditch Chaser who became trapped inside a Vanishing Cabinet for six months.",
    "Alastor (Mad-Eye) Moody – Retired Auror and member of the Order of the Phoenix. Impersonated by Barty Crouch Jr. in his scheme to enter Harry into the Triwizard Tournament. Killed by Voldemort.",
    "Theodore Nott – Slytherin student in the same year as Harry Potter, and son of a Death Eater.",
    "Nott Sr – Theodore Nott's father. Death Eater.",
    "Bob Ogden – Leader of the Department of Magical Law Enforcement Squad in the 1920s. Turned the Gaunt family over to the Wizengamot for using magic in front of a Muggle. Died before Harry Potter's sixth year.",
    "Garrick Ollivander – Wandmaker and owner of the Ollivanders wand shop. Kidnapped by the Malfoy family for several months until freed by Harry, Ron, and Hermione.",
    "Pansy Parkinson – Slytherin student in Harry's year. Prefect and member of the Inquisitorial Squad.",
    "Padma Patil – Ravenclaw student in Harry's year. Identical twin sister of Gryffindor student Parvati Patil, and a member of Dumbledore's Army.",
    "Parvati Patil – Gryffindor student in Harry's year and Padma's identical twin sister. Member of Dumbledore's Army.",
    "Peter Pettigrew – Death Eater and former school friend of James Potter, Sirius Black and Remus Lupin. Betrays Harry's parents James and Lily Potter to Voldemort, resulting in their deaths. Pettigrew is first introduced in the series as Ron Weasley's pet rat Scabbers. He is strangled to death by his own metal prosthetic hand after his loyalty towards Voldemort wavers upon Harry confronting him about having previously spared Pettigrew's life.",
    "Antioch, Cadmus, and Ignotus Peverell – Three brothers who were the original owners of the Elder Wand, the Resurrection Stone, and the Invisibility Cloak, respectively.",
    "Irma Pince – Hogwarts librarian.",
    "Sturgis Podmore – Member of the Order of the Phoenix.",
    "Poppy Pomfrey – Hogwarts school nurse.",
    "Harry Potter – The main character of the series. Orphaned son of James and Lily Potter. Gryffindor student at Hogwarts, and co-founder and first leader of Dumbledore's Army. The husband of Ginny Weasley, father of James Sirius, Albus Severus and Lily Luna Potter.",
    "James Potter – Harry Potter's father and member of the Order of the Phoenix. Killed along with his wife Lily by Lord Voldemort prior to the start of the series.",
    "Lily Potter – Harry Potter's mother and member of the Order of the Phoenix. Killed by Lord Voldemort.",
    "Albus Severus Potter – Second child of Harry Potter and Ginny Weasley.",
    "James Sirius Potter – Harry and Ginny's first child.",
    "Lily Luna Potter – Harry and Ginny's third child.",
    "Quirinus Quirrell – Defence Against the Dark Arts professor in Harry Potter's first year. Possessed by Lord Voldemort.",
    "Helena Ravenclaw/The Grey Lady – Daughter of house founder Rowena Ravenclaw. Stole and hid her mother's diadem, and became Ravenclaw's house ghost after being killed by the Bloody Baron.",
    "Rowena Ravenclaw – One of the four founders of Hogwarts School of Witchcraft and Wizardry, and founder of the Ravenclaw house.",
    "Delphi Riddle – The main antagonist of Harry Potter and the Cursed Child and daughter of Voldemort and Bellatrix Lestrange who tries to bring Voldemort back to life by completing a prophecy. Been imprisoned in Azkaban by Harry Potter, Ron Weasley, Hermione Granger, Draco Malfoy, Ginny Weasley.",
    "Mary Riddle – Thomas Riddle Sr.'s Muggle wife, and Thomas Riddle Jr.'s mother. Killed by her grandson, Lord Voldemort.",
    "Thomas Riddle Sr. – Mary's Muggle husband and Thomas Riddle Jr.'s father. Killed by Voldemort.",
    "Thomas Riddle Jr. – Voldemort's Muggle father and Merope Gaunt's husband. Killed by his son, Lord Voldemort.",
    "Thomas Marvolo Riddle – Slytherin student who became Lord Voldemort.",
    "Demelza Robins – Gryffindor student and Quidditch Chaser.",
    "Augustus Rookwood – Death Eater and spy working in the Department of Mysteries.",
    "Thorfinn Rowle – Death Eater.",
    "Albert Runcorn – Ministry of Magic employee whose chief function was as an investigator of alleged Muggle-borns.",
    "Newt Scamander – Magizoologist and author of Fantastic Beasts and Where to Find Them. Main character in the Fantastic Beasts film series. Expelled Hogwarts student who excels in curing different sicknesses.",
    "Rufus Scrimgeour – Head of the Auror Office who replaces Cornelius Fudge as Minister for Magic. Killed by Death Eaters.",
    "Kingsley Shacklebolt – Auror and member of the Order of the Phoenix. Replaces Pius Thicknesse as Minister for Magic.",
    "Stan Shunpike – Conductor of the triple-decker Knight Bus. Jailed in Azkaban on suspicions of being a Death Eater.",
    "Aurora Sinistra – Astronomy professor at Hogwarts.",
    "Rita Skeeter – Reporter and tabloid journalist for the Daily Prophet.",
    "Horace Slughorn – Former Hogwarts Potions professor and Head of Slytherin House, whose charges included Tom Riddle. Returned to Hogwarts to teach Potions in Harry's sixth year.",
    "Salazar Slytherin – One of the four founders of Hogwarts School of Witchcraft and Wizardry, and founder of the Slytherin house.",
    "Zacharias Smith – Hufflepuff Quidditch Chaser in Harry's year. Member of Dumbledore's Army.",
    "Severus Snape – Potions and later Defence Against the Dark Arts professor at Hogwarts. Head of Slytherin House, and member of both the Death Eaters and the Order of the Phoenix as a double agent spying for Dumbledore.",
    "Alicia Spinnet – Gryffindor student two years above Harry. Quidditch Chaser and member of Dumbledore's Army.",
    "Pomona Sprout – Hogwarts Herbology professor and Head of Hufflepuff House.",
    "Pius Thicknesse – Minister for Magic while under the Imperius Curse. Replaced by Kingsley Shacklebolt.",
    "Dean Thomas – Gryffindor student in Harry's year. Member of Dumbledore's Army.",
    "Andromeda Tonks – Sister of Bellatrix Lestrange and Narcissa Malfoy, and the mother of Nymphadora Tonks. Disowned by her family for marrying Muggle-born Ted Tonks.",
    "Nymphadora Tonks – Ted and Andromeda's daughter. Auror and member of the Order of the Phoenix. She marries Remus Lupin and becomes the mother of a son, Teddy, before she and Remus are killed in the Battle of Hogwarts.",
    "Ted Tonks – Andromeda's Muggle-born husband, and the father of Nymphadora Tonks. Killed by Snatchers.",
    "Sybill Trelawney – Hogwarts Divination professor. Predicted the prophecy that prompted Lord Voldemort to go after the Potters.",
    "Wilkie Twycross – Hogwarts Apparition instructor who works in the Department of Magical Transportation.",
    "Dolores Umbridge – Senior Undersecretary to the Minister for Magic, Hogwarts High Inquisitor and temporary Headmistress of Hogwarts. She becomes Defence Against the Dark Arts professor in Harry Potter's fifth year, and joins in the persecution of half-bloods and Muggle-borns under Voldemort. Sentenced to life imprisonment in Azkaban.",
    "Emmeline Vance – Member of the Order of the Phoenix. Killed by Death Eaters.",
    "Romilda Vane – Gryffindor student who unsuccessfully tries to romance Harry.",
    "Septima Vector – Arithmancy professor at Hogwarts.",
    "Lord Voldemort (Tom Marvolo Riddle) – The villain of the series. Murderer of Harry Potter's parents and many others in his quest for immortality and absolute power.",
    "Myrtle Warren/Moaning Myrtle – Muggle-born Ravenclaw student during Tom Riddle's time at Hogwarts. Killed by the Basilisk in a girls' bathroom, which she continued to haunt after her death.",
    "Arthur Weasley – Muggle-obsessed Ministry of Magic employee, and member of the Order of the Phoenix. Husband of Molly Weasley, father of Bill, Charlie, Percy, Fred, George, Ron, and Ginny Weasley.",
    "Bill Weasley – Oldest son of Arthur and Molly Weasley, and Gringotts employee. Marries Fleur Delacour.",
    "Charlie Weasley – Second son of Arthur and Molly Weasley. Member of the Order of the Phoenix. Works with dragons in Romania.",
    "Fred Weasley – Son of Arthur and Molly Weasley and identical twin brother of George Weasley. Gryffindor Quidditch Beater and member of Dumbledore's Army, later co-owner of joke shop Weasleys' Wizard Wheezes. Killed in the Battle of Hogwarts.",
    "George Weasley – Son of Arthur and Molly Weasley and identical twin brother of Fred Weasley. Gryffindor Quidditch Beater and member of Dumbledore's Army. Co-owner of Weasleys' Wizard Wheezes. Marries Angelina Johnson.",
    "Ginny Weasley – Only daughter and youngest child of Arthur and Molly Weasley. Gryffindor student one year below Harry, Quidditch Seeker and Chaser, and member of Dumbledore's Army. Married to Harry Potter.",
    "Hugo Weasley – Son of Ron Weasley and Hermione Granger, brother of Rose Weasley.",
    "Molly Weasley – Wife of Arthur Weasley and mother of Bill, Charlie, Percy, Fred, George, Ron, and Ginny. Member of the Order of the Phoenix.",
    "Percy Weasley – Third son of Arthur and Molly Weasley. Gryffindor prefect and Head Boy, then Ministry of Magic employee, during which he becomes estranged from his family before joining them in fighting the Death Eaters in the Battle of Hogwarts.",
    "Ron Weasley – Youngest son of Arthur and Molly Weasley who is best friends with Harry Potter and Hermione Granger. Gryffindor Quidditch Keeper, prefect, and co-founder of Dumbledore's Army.",
    "Oliver Wood – Gryffindor Quidditch Keeper and captain four years above Harry.",
    "Rose Weasley – Daughter of Ron Weasley and Hermione Granger. Sister of Hugo Weasley.",
    "Corban Yaxley – Death Eater. Head of Magical Law Enforcement under Voldemort's regime.",
    "Blaise Zabini – Slytherin student in Harry's year."
]